repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-docstring-first
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        #args: ['--ignore=E0401,E1101,E1102,R0913,R0914,W0703,E0602,C0103,C0114, W0102,C0330,C0326,W0107,R1716,R0902,E0611,E1124","--fail-under=5.0']
