name: Python Application test with GitHub Actions
on: [push]
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      -uses: actions/checkout@v2
      -name: Set up Python 3.10
      uses: actions/setup-python@v1


    

       
        
        
        
        
